# Numpy

Numpy is fast since it has bindings to C

## Installation
pip install numpy

## Vectors

Typically these are 1 d arrays

## Matrices

Typically are 2d but can still have one row or one column

## Numpy Arrays

In [1]:
# Creating a List
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
# Storing list as numpy array for speed
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
# Creating a 3x3 matrix
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
# Storing them as numpy array for speed
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# Creating a numpy array of numbers from 0 to 9
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# Creating a numpy array of numbers from 0 to 10 with step 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
# Creating an array of zeros
np.zeros(3)

array([0., 0., 0.])

In [11]:
# Creating a matrix of zeros
np.zeros((5,5)) # 5 rows and 5 columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
# Creating an array of ones
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
# Creating a matrix of ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0,5,10) # start=0 stop=5 10 evenly spaced points

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
# Creating Identity matix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5) # creates 5 random values from a uniform distribution

array([0.75368874, 0.26682695, 0.96203536, 0.9491322 , 0.3007006 ])

In [17]:
np.random.rand(5,5)

array([[0.59775048, 0.95274533, 0.90516098, 0.14335287, 0.89040338],
       [0.1745053 , 0.5552862 , 0.80182452, 0.35334269, 0.93727708],
       [0.63455439, 0.93157773, 0.89760086, 0.9584607 , 0.20589694],
       [0.44297353, 0.49465543, 0.80753521, 0.90328364, 0.85442468],
       [0.45088205, 0.66348575, 0.22367412, 0.97543738, 0.27708679]])

In [18]:
np.random.randn(2) # Creates random values from a standard normal distribution

array([-0.36353466,  1.03653356])

In [19]:
np.random.randn(2,3)

array([[ 2.22502047, -0.76962026, -0.2278712 ],
       [ 0.92226324, -0.59103349,  0.7169836 ]])

In [20]:
np.random.randint(1,100,10) # 10 random integers excluding 100

array([28, 13,  7, 22, 74, 42, 71, 62, 45, 75])

In [21]:
arr1 = np.arange(25)

In [22]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr = np.random.randint(0,50,10)

In [24]:
ranarr

array([41, 48, 13,  5, 43, 18, 23, 32, 26, 46])

In [25]:
arr1.reshape(5,5) # Converting an array of length 25 to 5x5 matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
arr1.reshape(5,10) # Demonstrating reshape error

ValueError: cannot reshape array of size 25 into shape (5,10)

In [27]:
ranarr.max()# Max value in array

48

In [28]:
ranarr.min()# Min value in array

5

In [29]:
ranarr.argmin() # returns index of min value

3

In [30]:
ranarr.argmax()# return index of max value

1

In [31]:
arr.shape # dimension of array

(3,)

In [32]:
arr1.shape

(25,)

In [33]:
arr1.dtype# Data Type of an array

dtype('int32')

In [34]:
arr[2]# Demonstrating indexing an array at position 2

3

In [35]:
arr1[2:5]# Extracting a part of an array from position 2 to 4

array([2, 3, 4])

In [36]:
arr[:6] # Extracting a part of an array from 0 to 5

array([1, 2, 3])

In [37]:
arr1[2:] # Extracting a part of an array from 2 till the end

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24])

In [38]:
arr1[0:5] = 100 # Changig values stores in an from position 0 to 4

In [39]:
arr1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [40]:
slice_of_arr = arr1[6:12] # Demonstrating that changing a slice of array also affects the original

In [41]:
slice_of_arr

array([ 6,  7,  8,  9, 10, 11])

In [42]:
slice_of_arr[:] = 99

In [43]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [44]:
arr1

array([100, 100, 100, 100, 100,   5,  99,  99,  99,  99,  99,  99,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [45]:
arr_copy = arr1.copy() # Demonstrating how to copy an array

In [46]:
arr_copy

array([100, 100, 100, 100, 100,   5,  99,  99,  99,  99,  99,  99,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [47]:
arr_copy[:] = -1

In [48]:
arr_copy

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1])

In [49]:
arr1

array([100, 100, 100, 100, 100,   5,  99,  99,  99,  99,  99,  99,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [50]:
arr_2d = np.array([[5,10,5],[20,25,30],[35,60,23]])# Demonstrating how to index a matrix

In [51]:
arr_2d

array([[ 5, 10,  5],
       [20, 25, 30],
       [35, 60, 23]])

In [52]:
arr_2d[0][0]

5

In [53]:
arr_2d[0]

array([ 5, 10,  5])

In [54]:
arr_2d[1,2]

30

In [55]:
arr_2d[:2,1:]

array([[10,  5],
       [25, 30]])

In [56]:
arr > 5 # Demonstrating how to filter an array

array([False, False, False])

In [57]:
bool_arr = arr > 5

In [58]:
bool_arr

array([False, False, False])

In [59]:
arr[bool_arr]

array([], dtype=int32)

In [60]:
arr1[arr1<3]

array([], dtype=int32)

In [61]:
arr_2d1 = np.arange(50).reshape(5,10)

In [62]:
arr_2d1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [63]:
arr_2d1[2:,4:7]

array([[24, 25, 26],
       [34, 35, 36],
       [44, 45, 46]])

In [64]:
arr2 = np.arange(0,11)

In [65]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr2 + arr2 # Addition fo arrays

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [67]:
arr2 - arr2 # Subtracting arrays

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [68]:
arr2 * arr2 # Multiplying arrays

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [69]:
arr2- 100 # Subtracting 100 for all values stored in an arrau

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [70]:
arr2/arr2 # Divsision of arrays

C:\Users\dsouz\AppData\Local\Temp\ipykernel_32164\4263725751.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr2/arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [71]:
1/arr2

C:\Users\dsouz\AppData\Local\Temp\ipykernel_32164\1672552411.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr2


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [72]:
arr2 **2 # Square of all array values

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [73]:
np.sqrt(arr2) # Square root of all array values

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [74]:
np.exp(arr2) # Exponential operation

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

https://numpy.org/doc/stable/reference/ufuncs.html - refer this for more info