# Numpy

Numpy is fast since it has bindings to C

## Installation
pip install numpy

## Vectors

Typically these are 1 d arrays

## Matrices

Typically are 2d but can still have one row or one column

## Numpy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5)) # 5 rows and 5 columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0,5,10) # start stop 10 evenly spaced points

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
# Creating Identity matix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5) # creates 5 random values from a uniform distribution

array([0.37642235, 0.24446479, 0.09610496, 0.42740457, 0.85770178])

In [17]:
np.random.rand(5,5)

array([[0.92949065, 0.22946936, 0.25931583, 0.75884414, 0.84525602],
       [0.03488307, 0.41637959, 0.84953797, 0.02592859, 0.97551915],
       [0.47421443, 0.59457121, 0.07373446, 0.5364154 , 0.71509745],
       [0.1127583 , 0.81682009, 0.736424  , 0.76737897, 0.00411042],
       [0.82608669, 0.5473824 , 0.54584637, 0.30813481, 0.19575808]])

In [18]:
np.random.randn(2) # Creates random values from a standard normal distribution

array([-0.54604377, -0.5681554 ])

In [19]:
np.random.randn(2,3)

array([[ 1.20202474,  0.59427095, -0.80063173],
       [-0.12465828,  0.8949834 ,  0.24518332]])

In [20]:
np.random.randint(1,100,10) # 10 random integers excluding 100

array([38, 93, 82, 96, 91, 94, 19, 16, 62, 84])

In [21]:
arr1 = np.arange(25)

In [22]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr = np.random.randint(0,50,10)

In [24]:
ranarr

array([20,  5, 44, 22, 34, 11,  4, 22,  4, 16])

In [26]:
arr1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
arr1.reshape(5,10)

ValueError: cannot reshape array of size 25 into shape (5,10)

In [29]:
ranarr.max()

44

In [32]:
ranarr.min()

4

In [33]:
ranarr.argmin() # returns index

6

In [34]:
ranarr.argmax()

2

In [35]:
arr.shape

(3,)

In [36]:
arr1.shape

(25,)

In [37]:
arr1.dtype

dtype('int32')

In [39]:
arr[2]

3

In [40]:
arr1[2:5]

array([2, 3, 4])

In [41]:
arr[:6]

array([1, 2, 3])

In [43]:
arr1[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24])

In [44]:
arr1[0:5] = 100

In [45]:
arr1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [46]:
slice_of_arr = arr1[6:12]

In [47]:
slice_of_arr

array([ 6,  7,  8,  9, 10, 11])

In [48]:
slice_of_arr[:] = 99

In [49]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [50]:
arr1

array([100, 100, 100, 100, 100,   5,  99,  99,  99,  99,  99,  99,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [51]:
arr_copy = arr1.copy()

In [52]:
arr_copy

array([100, 100, 100, 100, 100,   5,  99,  99,  99,  99,  99,  99,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [53]:
arr_copy[:] = -1

In [54]:
arr_copy

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1])

In [55]:
arr1

array([100, 100, 100, 100, 100,   5,  99,  99,  99,  99,  99,  99,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [56]:
arr_2d = np.array([[5,10,5],[20,25,30],[35,60,23]])

In [57]:
arr_2d

array([[ 5, 10,  5],
       [20, 25, 30],
       [35, 60, 23]])

In [58]:
arr_2d[0][0]

5

In [59]:
arr_2d[0]

array([ 5, 10,  5])

In [61]:
arr_2d[1,2]

30

In [62]:
arr_2d[:2,1:]

array([[10,  5],
       [25, 30]])

In [63]:
arr > 5

array([False, False, False])

In [64]:
bool_arr = arr > 5

In [65]:
bool_arr

array([False, False, False])

In [66]:
arr[bool_arr]

array([], dtype=int32)

In [67]:
arr1[arr1<3]

array([], dtype=int32)

In [68]:
arr_2d1 = np.arange(50).reshape(5,10)

In [69]:
arr_2d1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [70]:
arr_2d1[2:,4:7]

array([[24, 25, 26],
       [34, 35, 36],
       [44, 45, 46]])

In [72]:
arr2 = np.arange(0,11)

In [73]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr2 + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [75]:
arr2 - arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [78]:
arr2 * arr2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [79]:
arr2- 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [80]:
arr2/arr2

C:\Users\dsouz\AppData\Local\Temp\ipykernel_15340\4263725751.py:1: RuntimeWarning: invalid value encountered in divide
  arr2/arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [81]:
1/arr2

C:\Users\dsouz\AppData\Local\Temp\ipykernel_15340\1672552411.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr2


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [82]:
arr2 **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [83]:
np.sqrt(arr2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [84]:
np.exp(arr2)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

https://numpy.org/doc/stable/reference/ufuncs.html - refer this for more info